// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Prisma CLI operations use Neon's direct connection. Application runtime
    // continues to use the pooled DATABASE_URL through the driver adapter.
    url: process.env["DIRECT_URL"],
  },
});
